packages:
  - apps/*
  - packages/*

overrides:
  '@nestjs/swagger>js-yaml': 5.2.2

allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': false
  esbuild: true
  prisma: true
  unrs-resolver: true
